//package com.securevault19.securevault2019.record;
//
//import androidx.room.Entity;
//
//import java.util.Date;
//import java.sql.Timestamp;
//
//
//@Entity(tableName = "website_table")
//public class Website extends Record {
//
////Using a default Constructor.
//
////    @PrimaryKey(autoGenerate = true)
////    public int recordID;
//
//
//    // Exclusive variables
//    private String userName;
//    private String other;          // for additional signing details such as asved authentications question\answers
//
//    public Website() {
//        setDateCreated(dateCreated);
//        setLastModified(lastModified);
//        setCategory(category);
//    }
//
//
//    // Setters
//
//    public void setUserName(String userName) {
////        editText = editText.findViewById(R.id.userName);
////        this.userName = editText.getText().toString().trim();
//        this.userName = userName;
//    }
//
//    public void setOther(String other) {
//        this.other = other;
//    }
//
//
//// Override Setters
//
//    @Override
//    public void setRecordID(int recordID) {
//        // generated by the program
//        // @primary Key = autoGenerate = true
//    }
//
//    @Override
//    public void setTitle(String title) {
////        editText = editText.findViewById(R.id.title);
////        this.title = editText.getText().toString().trim();
//        this.title = title;
//    }
//
//    @Override
//    public void setPassword(String password) {
////        editText = editText.findViewById(R.id.password);
////        this.password = editText.getText().toString().trim();
//        this.password = password;
//    }
//
//    @Override
//    public void setWebsite(String website) {
////        editText = editText.findViewById(R.id.website);
////        this.website = editText.getText().toString().trim();
//        this.website = website;
//    }
//
//    @Override
//    public void setEmail(String email) {
////        editText = editText.findViewById(R.id.email);
////        this.email = editText.getText().toString().trim();
//        this.email = email;
//    }
//
//    @Override
//    public void setExpiringDate(String expiringDate) {
//        //if user didn't insert Expiring Date.
////        if (expiringDate == null) {
////
////            Calendar cal = Calendar.getInstance();
////            cal.add(Calendar.MONTH, 4);
////
////            this.expiringDate = cal.toString();
////
////        } else {
//        this.expiringDate = expiringDate;
//    }
//
//
//    @Override
//    public void setDateCreated(String dateCreated) {
//        Date date = new Date();
//
//        Timestamp timeStamp = new Timestamp(date.getTime());
//
//        this.dateCreated = timeStamp.toString();
//
//    }
//
//    @Override
//    public void setLastModified(String lastModified) {
////        editText = editText.findViewById(R.id.userName);
////        this.userName = editText.getText().toString().trim();
//        Date date = new Date();
//
//        Timestamp timeStamp = new Timestamp(date.getTime());
//
//        this.lastModified = timeStamp.toString();
//    }
//
//    @Override
//    public void setCategory(String category) {
//        this.category = "Website";
//    }
//
//
//    // Getters
//
//
//    public String getUserName() {
//        return userName;
//    }
//
//    public String getOther() {
//        return other;
//    }
//
//    // Override Getters
//
//    @Override
//    public int getRecord_ID() {
//        return recordID;
//    }
//
//    @Override
//    public String getTitle() {
//        return title;
//    }
//
//    @Override
//    public String getPassword() {
//        return password;
//    }
//
//    @Override
//    public String getWebsite() {
//        return website;
//    }
//
//    @Override
//    public String getEmail() {
//        return email;
//    }
//
//    @Override
//    public String getExpiringDate() {
//        return expiringDate;
//    }
//
//    @Override
//    public String getDateCreated() {
//        return dateCreated;
//    }
//
//    @Override
//    public String getLastModified() {
//        return lastModified;
//    }
//
//    @Override
//    public String getCategory() {
//        return category;
//    }
//
//    @Override
//    public void addCategory() {
//
//    }
//
//    @Override
//    public void addTextInbox() {
//
//    }
//
//    public void show() {
//
//    }
//
//}
